# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8dO6xS6QB5gxzKoFT6qY2zxExnfAqyY
"""

!pip install pillow

import os
from PIL import Image

INPUT_DIR = "/content/drive/MyDrive/Final_year_project/Optic Glioma/disease_images"    # your Drive folder
OUTPUT_DIR = "/content/drive/MyDrive/Final_year_project/refined images" # output folder
IMG_SIZE = (256, 256)

ALLOWED_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif")

def convert_and_save(image_path, save_path):
    with Image.open(image_path) as img:
        img = img.convert("L")            # Grayscale (MANDATORY)
        img = img.resize(IMG_SIZE)        # Resize to 256x256
        img.save(save_path, format="PNG") # Save as PNG

for root, dirs, files in os.walk(INPUT_DIR):
    for file in files:
        if file.lower().endswith(ALLOWED_EXTENSIONS):
            class_name = os.path.basename(root)
            input_path = os.path.join(root, file)

            output_class_dir = os.path.join(OUTPUT_DIR, class_name)
            os.makedirs(output_class_dir, exist_ok=True)

            output_file = os.path.splitext(file)[0] + ".png"
            output_path = os.path.join(output_class_dir, output_file)

            try:
                convert_and_save(input_path, output_path)
                print(f"[OK] {input_path} → {output_path}")
            except Exception as e:
                print(f"[ERROR] {input_path} | {e}")

print("\n✅ ALL DRIVE IMAGES CONVERTED TO PNG")