# -*- coding: utf-8 -*-
"""counting_the_images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKTiSn5SfNyiGU91gOeDHkOj8UCMvaCx
"""

import os

# ===================== CONFIG =====================
DATASET_BASE = "/content/drive/MyDrive/module_2_disease_classifier/balanced_dataset"

DISEASES = [
    "Moyamoya_Disease_with_Intraventricular_Hemorrhage",
    "Neurofibromatosis_Type_1_NF1",
    "Optic_Glioma",
    "Tuberous_Sclerosis"
]

SPLITS = ["train", "val", "test"]
CLASSES = ["disease", "normal"]
IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".bmp")
# =================================================

def count_images(folder):
    if not os.path.exists(folder):
        return 0
    return sum(
        1 for f in os.listdir(folder)
        if f.lower().endswith(IMAGE_EXTS)
    )

print("\n📊 IMAGE COUNT REPORT (Balanced Dataset)\n")

for disease in DISEASES:
    print(f"========== {disease} ==========")
    for split in SPLITS:
        for cls in CLASSES:
            path = os.path.join(DATASET_BASE, disease, split, cls)
            count = count_images(path)
            print(f"{split.upper()} | {cls.capitalize():7}: {count}")
    print()

print("✅ IMAGE COUNT COMPLETED")

import os

# ===================== CONFIG =====================
BASE_DIR = "/content/drive/MyDrive/module_2_disease_classifier/balanced_dataset"
# =================================================

def print_folder_structure(base_path, indent=0):
    if not os.path.exists(base_path):
        print("❌ Path does not exist:", base_path)
        return

    prefix = "│   " * indent
    print(f"{prefix}├── {os.path.basename(base_path)}/")

    try:
        items = sorted(os.listdir(base_path))
    except PermissionError:
        print(f"{prefix}│   ❌ Permission Denied")
        return

    for item in items:
        item_path = os.path.join(base_path, item)
        if os.path.isdir(item_path):
            print_folder_structure(item_path, indent + 1)
        else:
            print(f"{prefix}│   ├── {item}")

print("\n📁 FOLDER STRUCTURE\n")
print_folder_structure(BASE_DIR)
print("\n✅ DONE")

import os
import csv
import json

# ===================== CONFIG =====================
DATASET_BASE = "/content/drive/MyDrive/module_2_disease_classifier/balanced_dataset"

DISEASES = [
    "Moyamoya_Disease_with_Intraventricular_Hemorrhage",
    "Neurofibromatosis_Type_1_NF1",
    "Optic_Glioma",
    "Tuberous_Sclerosis"
]

SPLITS = ["train", "val", "test"]
CLASSES = ["disease", "normal"]
IMAGE_EXTS = (".png", ".jpg", ".jpeg", ".bmp")

OUTPUT_DIR = "/content/drive/MyDrive/module_2_disease_classifier"
CSV_FILE  = os.path.join(OUTPUT_DIR, "image_count_report.csv")
JSON_FILE = os.path.join(OUTPUT_DIR, "image_count_report.json")
# =================================================

def count_images_recursive(folder):
    count = 0
    if not os.path.exists(folder):
        return 0
    for root, _, files in os.walk(folder):
        for f in files:
            if f.lower().endswith(IMAGE_EXTS):
                count += 1
    return count

# ===================== COUNTING =====================
rows = []
json_data = {}

for disease in DISEASES:
    json_data[disease] = {}
    for split in SPLITS:
        json_data[disease][split] = {}
        for cls in CLASSES:
            path = os.path.join(DATASET_BASE, disease, split, cls)
            count = count_images_recursive(path)

            rows.append([
                disease,
                split,
                cls,
                count
            ])

            json_data[disease][split][cls] = count

# ===================== SAVE CSV =====================
with open(CSV_FILE, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Disease", "Split", "Class", "Image_Count"])
    writer.writerows(rows)

# ===================== SAVE JSON =====================
with open(JSON_FILE, "w") as f:
    json.dump(json_data, f, indent=4)

print("✅ IMAGE COUNTS SAVED SUCCESSFULLY")
print("📄 CSV :", CSV_FILE)
print("📄 JSON:", JSON_FILE)